# Languages
# Each language key stands as its language code
# ################################
en:
  languageName: English
  weight: 1
  flag: "ğŸ‡¬ğŸ‡§"

# Secondary language
fr:
  languageName: FranÃ§ais
  weight: 2
  flag: "ğŸ‡«ğŸ‡·"

ja:
  languageName: æ—¥æœ¬èª
  weight: 3
  flag: "ğŸ‡¯ğŸ‡µ"
